# Generated by Django 3.2.13 on 2022-10-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='figurinha',
            name='jogador',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='figurinha',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='Codigo Figurinha'),
        ),
    ]
