# Generated by Django 3.2.13 on 2022-10-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_figurinha_selecao'),
    ]

    operations = [
        migrations.AddField(
            model_name='figurinha',
            name='escudo',
            field=models.BooleanField(null=True),
        ),
    ]
