# Generated by Django 3.2.13 on 2022-10-24 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_figurinha_escudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figurinha',
            name='estadio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ecommerce.estadio', verbose_name='Estadio'),
        ),
        migrations.AlterField(
            model_name='figurinha',
            name='selecao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ecommerce.selecao', verbose_name='Seleção'),
        ),
    ]
