# Generated by Django 3.2.13 on 2022-10-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20221024_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='nomeGrupo',
            field=models.CharField(max_length=20, verbose_name='Nome do Grupo'),
        ),
    ]
