# Generated by Django 3.2.13 on 2022-10-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_grupo_nomegrupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='nomeGrupo',
            field=models.CharField(max_length=1, verbose_name='Nome do Grupo'),
        ),
    ]
