# Generated by Django 3.2.13 on 2022-10-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_alter_grupo_nomegrupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='figurinha',
            name='codigo',
            field=models.CharField(max_length=20, null=True, verbose_name='Codigo Figurinha'),
        ),
        migrations.AlterField(
            model_name='figurinha',
            name='numero',
            field=models.IntegerField(null=True, verbose_name='Numero: '),
        ),
    ]
