# Generated by Django 3.2.13 on 2022-10-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_auto_20221026_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figurinha',
            name='numero',
            field=models.IntegerField(null=True, verbose_name='Numero '),
        ),
    ]
