# Generated by Django 3.2.13 on 2022-11-09 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_vendedor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrofig',
            name='vendedores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ecommerce.vendedor', verbose_name='Vendedor'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='fotoUsuario',
            field=models.ImageField(max_length=255, null=True, upload_to='filmes'),
        ),
        migrations.AlterField(
            model_name='cadastrofig',
            name='condicao',
            field=models.CharField(max_length=50),
        ),
    ]
